server:
  port: 8080
spring:
  application:
    name: gateway

services:
  member-service:
    url: http://localhost:8081
  conference-service:
    url: http://localhost:8082
  reservation-service:
    url: http://localhost:8083