#!/bin/bash
set -e
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
  CREATE DATABASE IF NOT EXISTS member_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  CREATE DATABASE IF NOT EXISTS conference_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  CREATE DATABASE IF NOT EXISTS reservation_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

  CREATE USER IF NOT EXISTS '${MEMBER_DB_USER}'@'%' IDENTIFIED BY '${MEMBER_DB_PASSWORD}';
  CREATE USER IF NOT EXISTS '${CONFERENCE_DB_USER}'@'%' IDENTIFIED BY '${CONFERENCE_DB_PASSWORD}';
  CREATE USER IF NOT EXISTS '${RESERVATION_DB_USER}'@'%' IDENTIFIED BY '${RESERVATION_DB_PASSWORD}';

  GRANT ALL PRIVILEGES ON member_service.* TO '${MEMBER_DB_USER}'@'%';
  GRANT ALL PRIVILEGES ON conference_service.* TO '${CONFERENCE_DB_USER}'@'%';
  GRANT ALL PRIVILEGES ON reservation_service.* TO '${RESERVATION_DB_USER}'@'%';

  FLUSH PRIVILEGES;
EOSQL